name: Check Database Types

on: [pull_request]

permissions:
  contents: read

jobs:
  check-database-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Initialize Supabase
        run: supabase init

      - name: Start Supabase database
        run: supabase db start

      - name: Verify generated types match Postgres schema
        run: |
          supabase gen types typescript --local > src/lib/types/database.types.ts
          if ! git diff --ignore-space-at-eol --exit-code --quiet src/lib/types/database.types.ts; then
            echo "❌ Database types are out of sync!"
            echo ""
            echo "The generated types differ from the committed src/lib/types/database.types.ts"
            echo ""
            echo "To fix this, run the following commands locally:"
            echo "  supabase db start"
            echo "  supabase gen types typescript --local > src/lib/types/database.types.ts"
            echo ""
            echo "Detected uncommitted changes after build. See status below:"
            git diff src/lib/types/database.types.ts
            exit 1
          fi
          echo "✅ Database types are in sync!"
